export const productCollections = [
  {
    eyebrow: "GLUTANEX",
    title: "Işıltı",
    scriptTitle: "rutini",
    description:
      "PDRN, glutatyon ve nem desteğini aynı rutinde değerlendirebileceğin seçilmiş GLUTANEX ürünleri.",
    backgroundClassName: "bg-site-mist",
    parallaxStrength: "1.2",
    reverseAutoplay: false,
    showcase: {
      image: "/images/home/glutanex-carousel-big/image-1.jpg",
      alt: "GLUTANEX günlük koruma ve bakım ürünleri",
      label: "Günlük koruma / seçilmiş bakım",
      distance: -116,
    },
    products: [
      {
        index: "01",
        brand: "GLUTANEX",
        name: "Glow Booster",
        category: "Yüz kremi",
        size: "50 ml",
        price: "1850 TL",
        image: "/images/urunler-ham/glutanex-glow-booster.webp",
        hoverImage: "/images/urunler-ham/glutanex-glow-booster-hover.webp",
        imageAlt: "GLUTANEX Glow Booster Crystal Radiance Capsule Cream",
        tone: "bg-[#dbe5e9]",
      },
      {
        index: "02",
        brand: "GLUTANEX",
        name: "Glow Therapy Eye Cream",
        category: "Göz çevresi",
        size: "30 ml",
        price: "1850 TL",
        image: "/images/urunler-ham/glutanex-glow-therapy-eye-cream.webp",
        hoverImage:
          "/images/urunler-ham/glutanex-glow-therapy-eye-cream-hover.webp",
        imageAlt: "GLUTANEX Glow Therapy Eye Cream",
        tone: "bg-[#e8dfd9]",
      },
      {
        index: "03",
        brand: "GLUTANEX",
        name: "Glow Therapy Milky Serum",
        category: "Serum",
        size: "30 ml",
        price: "1850 TL",
        image: "/images/urunler-ham/glutanex-glow-therapy-milky-serum.webp",
        hoverImage:
          "/images/urunler-ham/glutanex-glow-therapy-milky-serum-hover.webp",
        imageAlt: "GLUTANEX Glow Therapy Milky Serum",
        tone: "bg-[#efe0dc]",
      },
      {
        index: "04",
        brand: "GLUTANEX",
        name: "Glow Therapy Toner",
        category: "Tonik",
        size: "150 ml",
        price: "1400 TL",
        image: "/images/urunler-ham/glutanex-glow-therapy-toner.webp",
        hoverImage: "/images/urunler-ham/glutanex-glow-therapy-toner-hover.webp",
        imageAlt: "GLUTANEX Glow Therapy Toner",
        tone: "bg-[#e6e1d8]",
      },
      {
        index: "05",
        brand: "GLUTANEX",
        name: "Glow Therapy Gel-to-Foam Cleanser",
        category: "Temizleyici",
        size: "100 ml",
        price: "850 TL",
        image:
          "/images/urunler-ham/glutanex-glow-therapy-gel-to-foam-cleanser.webp",
        hoverImage:
          "/images/urunler-ham/glutanex-glow-therapy-gel-to-foam-cleanser-hover.webp",
        imageAlt: "GLUTANEX Glow Therapy Gel-to-Foam Cleanser",
        tone: "bg-[#dce7df]",
      },
    ],
  },
  {
    eyebrow: "GLUTANEX",
    title: "Koruma",
    scriptTitle: "dokusu",
    description:
      "Güneş koruması, leke odağı ve günlük ton eşitlemeyi birlikte düşünen bakım adımları.",
    backgroundClassName: "bg-site-paper",
    parallaxStrength: "1.28",
    reverseAutoplay: true,
    showcase: {
      image: "/images/home/glutanex-carousel-2-big/image-1.jpg",
      alt: "GLUTANEX ton eşitleme ve güneş koruma ürünleri",
      label: "Ton eşitleme / güneş bakımı",
      distance: -132,
    },
    products: [
      {
        index: "01",
        brand: "GLUTANEX",
        name: "Sun Stick SPF50+",
        category: "Güneş stick",
        size: "30 g",
        price: "1500 TL",
        image: "/images/urunler-ham/glutanex-glow-sun-stick-spf50+.webp",
        hoverImage:
          "/images/urunler-ham/glutanex-glow-sun-stick-spf50+-hover.webp",
        imageAlt: "GLUTANEX Sun Stick SPF50+ PA++++",
        tone: "bg-[#e9e6dc]",
      },
      {
        index: "02",
        brand: "GLUTANEX",
        name: "Glow Sun Cream Light SPF50+",
        category: "Güneş kremi",
        size: "50 ml",
        price: "1850 TL",
        image: "/images/urunler-ham/glutanex-glow-sun-cream-light-spf50+.webp",
        hoverImage:
          "/images/urunler-ham/glutanex-glow-sun-cream-light-spf50+-hover.webp",
        imageAlt: "GLUTANEX Glow Sun Cream Light SPF50+ PA++++",
        tone: "bg-[#e4dfe8]",
      },
      {
        index: "03",
        brand: "GLUTANEX",
        name: "Aloe Booster",
        category: "Jel krem",
        size: "200 ml",
        price: "1500 TL",
        image: "/images/urunler-ham/glutanex-aloe-booster.webp",
        hoverImage: "/images/urunler-ham/glutanex-aloe-booster-hover.webp",
        imageAlt: "GLUTANEX Aloe Vera Nemlendirici Jel Krem",
        tone: "bg-[#d8e4e3]",
      },
      {
        index: "04",
        brand: "GLUTANEX",
        name: "Spot Cream",
        category: "Leke bakımı",
        size: "20 ml",
        price: "980 TL",
        image: "/images/urunler-ham/glutanex-spot-cream.webp",
        hoverImage: "/images/urunler-ham/glutanex-spot-cream-hover.webp",
        imageAlt: "GLUTANEX Spot Cream",
        tone: "bg-[#eadfd6]",
      },
      {
        index: "05",
        brand: "GLUTANEX",
        name: "Deo Glow Balm",
        category: "Deodorant",
        size: "12.5 g",
        price: "650 TL",
        image: "/images/urunler-ham/glutanex-glow-deo-balm.webp",
        hoverImage: "/images/urunler-ham/glutanex-glow-deo-balm-hover.webp",
        imageAlt: "GLUTANEX Deo Glow Balm",
        tone: "bg-[#e3eadf]",
      },
    ],
  },
];
